### PR TITLE
Add myself as maintainer

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@maresb Thanks for being a maintainer. Could you please follow the instructions of the linter and change the meta.yaml accordingly?

**Comment by maresb** [comment]
@kmuehlbauer done. The linter looks happy now.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@maresb Thanks, 
let's try to rerender. If this doesn't work, we need to do this manually...

**Comment by maresb** [comment]
image

**Comment by maresb** [comment]
Well the other PR looks good. Couldn't we just merge that first?

**Comment by kmuehlbauer** [comment]
@maresb Usually it's good practise to rerender, especially if the PR is that old. I'll try to fix this later today.

**Comment by maresb** [comment]
I see. Unfortunately I don't have write permissions on the `regro-cf-autotick-bot` fork, presumably because I'm not a maintainer yet. Circular problem...

I'm about to go out, will probably be back later this evening. Thanks!

**Comment by maresb** [comment]
By the way, what's the complication? Is there anything beyond just adding `>=3.4` to the autotick PR and rerendering?

**Comment by kmuehlbauer** [comment]
I'll try exactly that later, but there might be more involved. I've asked in the gitter channel for guidance, so hopefully this get sorted out soon.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Weird, it looks like it's using Python 2.7.

**Comment by kmuehlbauer** [comment]
Yes, the py27 stuff would normally be removed by rerender, but somehow it doesn't work for the bot. I'll try to rerender manually, then.

**Pull request merged**
