### PR TITLE
add maintainer and rerender

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
ping  @maresb 

closes #6

**Comment by kmuehlbauer** [comment]
@maresb I rerendered locally on top of your patch. I'll merge if we get green. After that I'll rebase the bot branch (if it will let me do so), otherwise we can update the version manually...

**Comment by kmuehlbauer** [comment]
@maresb Welcome on board. Good to have another set of :eyes: to not miss an update again.

I just saw that you already incorporated the v0.8.1 within your patch. So this should now create the new version and after roughly one hour (CDN snycing time) the package should be available on the channel.

**Comment by maresb** [comment]
Excellent, thanks @kmuehlbauer! It's available now on `conda search`.

**Pull request merged**
